### ISSUE TITLE
Configuration offset is ignored

### ISSUE THREAD

**Issue by paul53** [mcm4iob/ioBroker.pid#105]
Der Offset aus der Konfiguration wird nicht in para.off übernommen, sondern ein vorhandener Wert wird bei Instanz-Start mit 0 überschrieben.

**Comment by mcm1957** [comment]
Controller scheint nach offs zu suchen während der restliche Code off verwendet.
... nach zu checken und ggF zu fixen ...

**Comment by mcm1957** [comment]
fixed with 1.0.0
