### ISSUE TITLE
Invertieren des Reglerausgangs sollte beschreibbar sein

### ISSUE THREAD

**Issue by fu-zhou** [mcm4iob/ioBroker.pid#188]
Hallo mal wieder, ich habe den nächsten Einsatz für den Regler: Wärme-/ Kälterückgewinnung über die Drehzahl der Wärmeräder in der Lüftung. Dazu muss ich den inv mit true oder false aus einem Skript beschreiben können, das geht aktuell nicht. Alternativ könnte ich kp auf einen negativen Wert setzen, der Adapter lässt aber nur positive Werte zu. Bei tn, tv, xp lassen sich negative Werte setzen. 

Hintergrund: wenn die Außenluft kälter ist, als die Raumluft, kann ich über die Erhöhung der Drehzahl die Zuluft mit der Abluft erwärmen. Im Sommer ist die Außenluft wärmer, als die Raumluft, d.h. ich kann über die Erhöhung der Drehzahl die Zuluft mit der Abluft kühlen. D.h. wenn  Temperatur Außenluft < Raumluft, dann inv = 0 und wenn Temperatur Außenluft > Raumluft, dann inv = 1 . Kannst du inv beschreibbar machen? Dann kannst du auch bei tn, tv, xp nur pos. Werte zulassen.

Danke vorab!

**Comment by mcm1957** [comment]
Reminder: check https://github.com/mcm4iob/ioBroker.pid/issues/97 too when processing this issue.

**Comment by mcm1957** [comment]
inv auf einen beschreibbaren State zu ändern sollte gehen. (Ich hoff ich komm endlich dazu das umzusetzen :-( )

tn,tv,xp im Bereich einzuschränken werde ich nicht machen, da dies ein breaking change wäre und proinzipiell kein (mir bekannter) Nachteil existiert hier auch negative Werte zuzulassen.
