### ISSUE TITLE
Invertieren ohne Funktion

### ISSUE THREAD

**Issue by quorle** [mcm4iob/ioBroker.pid#97]
Sobald man in den Einstellungen auf "Invertieren" drück, bekommt man keine Ausgabe mehr.

**Comment by mcm1957** [comment]
Was bedeutet keine Ausgabe?
Stürzt der Adapter ab oder ist damit gemeint, dass sich der Wert Y nicht mehr ändert?
Welchen Wert nimmt der State LIM an ?

Bitte die Option "Protokollberechnung" / "log calculation" aktivieren und das logfile posten.

Ich vermute mal, dass der Regler nach dem Invertieren am oberen / unteren Grenzwert ansteht. Das sollte sich aber an Hand des LIM states sowei des Rchen-Logs klären lassen.

**Comment by quorle** [comment]
Aktuell kann ich leider nichts zum oben genannten Problem sagen und testen, da der Adapter nicht mehr startet und reihenweise Fehler auswirft.

Fehlerprotokoll:

`<html>
<body>


host.ioBroker | 2023-07-09 19:39:57.287 | error | instance system.adapter.pid.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
-- | -- | -- | --
pid.0 | 2023-07-09 19:39:56.403 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
pid.0 | 2023-07-09 19:39:56.402 | info | terminating
pid.0 | 2023-07-09 19:39:56.394 | error | Cannot read properties of undefined (reading 'pidCtrl')
pid.0 | 2023-07-09 19:39:56.394 | error | TypeError: Cannot read properties of undefined (reading 'pidCtrl') at Pid.chgAct (/opt/iobroker/node_modules/iobroker.pid/main.js:658:26) at Pid.onStateChange (/opt/iobroker/node_modules/iobroker.pid/main.js:388:35) at Pid.emit (node:events:513:28) at Immediate.<anonymous> (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:8406:53) at process.processImmediate (node:internal/timers:476:21)
pid.0 | 2023-07-09 19:39:56.394 | error | unhandled promise rejection: Cannot read properties of undefined (reading 'pidCtrl')
pid.0 | 2023-07-09 19:39:56.394 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
pid.0 | 2023-07-09 19:39:56.393 | error | Cannot read properties of undefined (reading 'pidCtrl')
pid.0 | 2023-07-09 19:39:56.393 | error | TypeError: Cannot read properties of undefined (reading 'pidCtrl') at Pid.chgAct (/opt/iobroker/node_modules/iobroker.pid/main.js:658:26) at Pid.onStateChange (/opt/iobroker/node_modules/iobroker.pid/main.js:388:35) at Pid.emit (node:events:513:28) at Immediate.<anonymous> (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:8406:53) at process.processImmediate (node:internal/timers:476:21)
pid.0 | 2023-07-09 19:39:56.393 | error | unhandled promise rejection: Cannot read properties of undefined (reading 'pidCtrl')
pid.0 | 2023-07-09 19:39:56.393 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
pid.0 | 2023-07-09 19:39:56.392 | error | Cannot read properties of undefined (reading 'pidCtrl')
pid.0 | 2023-07-09 19:39:56.392 | error | TypeError: Cannot read properties of undefined (reading 'pidCtrl') at Pid.chgAct (/opt/iobroker/node_modules/iobroker.pid/main.js:658:26) at Pid.onStateChange (/opt/iobroker/node_modules/iobroker.pid/main.js:388:35) at Pid.emit (node:events:513:28) at Immediate.<anonymous> (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:8406:53) at process.processImmediate (node:internal/timers:476:21)
pid.0 | 2023-07-09 19:39:56.392 | error | unhandled promise rejection: Cannot read properties of undefined (reading 'pidCtrl')
pid.0 | 2023-07-09 19:39:56.392 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
pid.0 | 2023-07-09 19:39:56.392 | error | Cannot read properties of undefined (reading 'pidCtrl')
pid.0 | 2023-07-09 19:39:56.392 | error | TypeError: Cannot read properties of undefined (reading 'pidCtrl') at Pid.chgAct (/opt/iobroker/node_modules/iobroker.pid/main.js:658:26) at Pid.onStateChange (/opt/iobroker/node_modules/iobroker.pid/main.js:388:35) at Pid.emit (node:events:513:28) at Immediate.<anonymous> (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:8406:53) at process.processImmediate (node:internal/timers:476:21)
pid.0 | 2023-07-09 19:39:56.392 | error | unhandled promise rejection: Cannot read properties of undefined (reading 'pidCtrl')
pid.0 | 2023-07-09 19:39:56.392 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
pid.0 | 2023-07-09 19:39:56.391 | error | Cannot read properties of undefined (reading 'pidCtrl')
pid.0 | 2023-07-09 19:39:56.391 | error | TypeError: Cannot read properties of undefined (reading 'pidCtrl') at Pid.chgAct (/opt/iobroker/node_modules/iobroker.pid/main.js:658:26) at Pid.onStateChange (/opt/iobroker/node_modules/iobroker.pid/main.js:388:35) at Pid.emit (node:events:513:28) at Immediate.<anonymous> (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:8406:53) at process.processImmediate (node:internal/timers:476:21)
pid.0 | 2023-07-09 19:39:56.391 | error | unhandled promise rejection: Cannot read properties of undefined (reading 'pidCtrl')
pid.0 | 2023-07-09 19:39:56.391 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
pid.0 | 2023-07-09 19:39:56.389 | error | Cannot read properties of undefined (reading 'pidCtrl')
pid.0 | 2023-07-09 19:39:56.389 | error | TypeError: Cannot read properties of undefined (reading 'pidCtrl') at Pid.chgAct (/opt/iobroker/node_modules/iobroker.pid/main.js:658:26) at Pid.onStateChange (/opt/iobroker/node_modules/iobroker.pid/main.js:388:35) at Pid.emit (node:events:513:28) at Immediate.<anonymous> (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:8406:53) at process.processImmediate (node:internal/timers:476:21)
pid.0 | 2023-07-09 19:39:56.389 | error | unhandled promise rejection: Cannot read properties of undefined (reading 'pidCtrl')
pid.0 | 2023-07-09 19:39:56.389 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
pid.0 | 2023-07-09 19:39:56.388 | error | Cannot read properties of undefined (reading 'pidCtrl')
pid.0 | 2023-07-09 19:39:56.388 | error | TypeError: Cannot read properties of undefined (reading 'pidCtrl') at Pid.chgAct (/opt/iobroker/node_modules/iobroker.pid/main.js:658:26) at Pid.onStateChange (/opt/iobroker/node_modules/iobroker.pid/main.js:388:35) at Pid.emit (node:events:513:28) at Immediate.<anonymous> (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:8406:53) at process.processImmediate (node:internal/timers:476:21)
pid.0 | 2023-07-09 19:39:56.388 | error | unhandled promise rejection: Cannot read properties of undefined (reading 'pidCtrl')
pid.0 | 2023-07-09 19:39:56.388 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
pid.0 | 2023-07-09 19:39:56.387 | error | Cannot read properties of undefined (reading 'pidCtrl')
pid.0 | 2023-07-09 19:39:56.387 | error | TypeError: Cannot read properties of undefined (reading 'pidCtrl') at Pid.chgAct (/opt/iobroker/node_modules/iobroker.pid/main.js:658:26) at Pid.onStateChange (/opt/iobroker/node_modules/iobroker.pid/main.js:388:35) at Pid.emit (node:events:513:28) at Immediate.<anonymous> (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:8406:53) at process.processImmediate (node:internal/timers:476:21)
pid.0 | 2023-07-09 19:39:56.387 | error | unhandled promise rejection: Cannot read properties of undefined (reading 'pidCtrl')
pid.0 | 2023-07-09 19:39:56.387 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
pid.0 | 2023-07-09 19:39:56.387 | error | Cannot read properties of undefined (reading 'pidCtrl')
pid.0 | 2023-07-09 19:39:56.387 | error | TypeError: Cannot read properties of undefined (reading 'pidCtrl') at Pid.chgAct (/opt/iobroker/node_modules/iobroker.pid/main.js:658:26) at Pid.onStateChange (/opt/iobroker/node_modules/iobroker.pid/main.js:388:35) at Pid.emit (node:events:513:28) at Immediate.<anonymous> (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:8406:53) at process.processImmediate (node:internal/timers:476:21)
pid.0 | 2023-07-09 19:39:56.387 | error | unhandled promise rejection: Cannot read properties of undefined (reading 'pidCtrl')
pid.0 | 2023-07-09 19:39:56.387 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
pid.0 | 2023-07-09 19:39:56.386 | error | Cannot read properties of undefined (reading 'pidCtrl')
pid.0 | 2023-07-09 19:39:56.386 | error | TypeError: Cannot read properties of undefined (reading 'pidCtrl') at Pid.chgAct (/opt/iobroker/node_modules/iobroker.pid/main.js:658:26) at Pid.onStateChange (/opt/iobroker/node_modules/iobroker.pid/main.js:388:35) at Pid.emit (node:events:513:28) at Immediate.<anonymous> (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:8406:53) at process.processImmediate (node:internal/timers:476:21)
pid.0 | 2023-07-09 19:39:56.386 | error | unhandled promise rejection: Cannot read properties of undefined (reading 'pidCtrl')
pid.0 | 2023-07-09 19:39:56.386 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
pid.0 | 2023-07-09 19:39:56.386 | error | Cannot read properties of undefined (reading 'pidCtrl')
pid.0 | 2023-07-09 19:39:56.386 | error | TypeError: Cannot read properties of undefined (reading 'pidCtrl') at Pid.chgAct (/opt/iobroker/node_modules/iobroker.pid/main.js:658:26) at Pid.onStateChange (/opt/iobroker/node_modules/iobroker.pid/main.js:388:35) at Pid.emit (node:events:513:28) at Immediate.<anonymous> (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:8406:53) at process.processImmediate (node:internal/timers:476:21)
pid.0 | 2023-07-09 19:39:56.386 | error | unhandled promise rejection: Cannot read properties of undefined (reading 'pidCtrl')
pid.0 | 2023-07-09 19:39:56.386 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
pid.0 | 2023-07-09 19:39:56.385 | error | Cannot read properties of undefined (reading 'pidCtrl')
pid.0 | 2023-07-09 19:39:56.385 | error | TypeError: Cannot read properties of undefined (reading 'pidCtrl') at Pid.chgAct (/opt/iobroker/node_modules/iobroker.pid/main.js:658:26) at Pid.onStateChange (/opt/iobroker/node_modules/iobroker.pid/main.js:388:35) at Pid.emit (node:events:513:28) at Immediate.<anonymous> (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:8406:53) at process.processImmediate (node:internal/timers:476:21)
pid.0 | 2023-07-09 19:39:56.385 | error | unhandled promise rejection: Cannot read properties of undefined (reading 'pidCtrl')
pid.0 | 2023-07-09 19:39:56.385 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
pid.0 | 2023-07-09 19:39:56.385 | error | Cannot read properties of undefined (reading 'pidCtrl')
pid.0 | 2023-07-09 19:39:56.385 | error | TypeError: Cannot read properties of undefined (reading 'pidCtrl') at Pid.chgAct (/opt/iobroker/node_modules/iobroker.pid/main.js:658:26) at Pid.onStateChange (/opt/iobroker/node_modules/iobroker.pid/main.js:388:35) at Pid.emit (node:events:513:28) at Immediate.<anonymous> (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:8406:53) at process.processImmediate (node:internal/timers:476:21)
pid.0 | 2023-07-09 19:39:56.384 | error | unhandled promise rejection: Cannot read properties of undefined (reading 'pidCtrl')
pid.0 | 2023-07-09 19:39:56.384 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
pid.0 | 2023-07-09 19:39:56.384 | error | Cannot read properties of undefined (reading 'pidCtrl')
pid.0 | 2023-07-09 19:39:56.384 | error | TypeError: Cannot read properties of undefined (reading 'pidCtrl') at Pid.chgAct (/opt/iobroker/node_modules/iobroker.pid/main.js:658:26) at Pid.onStateChange (/opt/iobroker/node_modules/iobroker.pid/main.js:388:35) at Pid.emit (node:events:513:28) at Immediate.<anonymous> (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:8406:53) at process.processImmediate (node:internal/timers:476:21)
pid.0 | 2023-07-09 19:39:56.384 | error | unhandled promise rejection: Cannot read properties of undefined (reading 'pidCtrl')
pid.0 | 2023-07-09 19:39:56.384 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
pid.0 | 2023-07-09 19:39:56.383 | error | Cannot read properties of undefined (reading 'pidCtrl')
pid.0 | 2023-07-09 19:39:56.383 | error | TypeError: Cannot read properties of undefined (reading 'pidCtrl') at Pid.chgAct (/opt/iobroker/node_modules/iobroker.pid/main.js:658:26) at Pid.onStateChange (/opt/iobroker/node_modules/iobroker.pid/main.js:388:35) at Pid.emit (node:events:513:28) at Immediate.<anonymous> (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:8406:53) at process.processImmediate (node:internal/timers:476:21)
pid.0 | 2023-07-09 19:39:56.383 | error | unhandled promise rejection: Cannot read properties of undefined (reading 'pidCtrl')
pid.0 | 2023-07-09 19:39:56.383 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
pid.0 | 2023-07-09 19:39:56.381 | error | Cannot read properties of undefined (reading 'pidCtrl')
pid.0 | 2023-07-09 19:39:56.381 | error | TypeError: Cannot read properties of undefined (reading 'pidCtrl') at Pid.chgAct (/opt/iobroker/node_modules/iobroker.pid/main.js:658:26) at Pid.onStateChange (/opt/iobroker/node_modules/iobroker.pid/main.js:388:35) at Pid.emit (node:events:513:28) at Immediate.<anonymous> (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:8406:53) at process.processImmediate (node:internal/timers:476:21)
pid.0 | 2023-07-09 19:39:56.381 | error | unhandled promise rejection: Cannot read properties of undefined (reading 'pidCtrl')
pid.0 | 2023-07-09 19:39:56.381 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
pid.0 | 2023-07-09 19:39:56.381 | error | Cannot read properties of undefined (reading 'pidCtrl')
pid.0 | 2023-07-09 19:39:56.381 | error | TypeError: Cannot read properties of undefined (reading 'pidCtrl') at Pid.chgAct (/opt/iobroker/node_modules/iobroker.pid/main.js:658:26) at Pid.onStateChange (/opt/iobroker/node_modules/iobroker.pid/main.js:388:35) at Pid.emit (node:events:513:28) at Immediate.<anonymous> (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:8406:53) at process.processImmediate (node:internal/timers:476:21)
pid.0 | 2023-07-09 19:39:56.380 | error | unhandled promise rejection: Cannot read properties of undefined (reading 'pidCtrl')
pid.0 | 2023-07-09 19:39:56.380 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
pid.0 | 2023-07-09 19:39:56.380 | error | Cannot read properties of undefined (reading 'pidCtrl')
pid.0 | 2023-07-09 19:39:56.380 | error | TypeError: Cannot read properties of undefined (reading 'pidCtrl') at Pid.chgAct (/opt/iobroker/node_modules/iobroker.pid/main.js:658:26) at Pid.onStateChange (/opt/iobroker/node_modules/iobroker.pid/main.js:388:35) at Pid.emit (node:events:513:28) at Immediate.<anonymous> (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:8406:53) at process.processImmediate (node:internal/timers:476:21)
pid.0 | 2023-07-09 19:39:56.380 | error | unhandled promise rejection: Cannot read properties of undefined (reading 'pidCtrl')
pid.0 | 2023-07-09 19:39:56.379 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
pid.0 | 2023-07-09 19:39:56.379 | error | Cannot read properties of undefined (reading 'pidCtrl')
pid.0 | 2023-07-09 19:39:56.379 | error | TypeError: Cannot read properties of undefined (reading 'pidCtrl') at Pid.chgAct (/opt/iobroker/node_modules/iobroker.pid/main.js:658:26) at Pid.onStateChange (/opt/iobroker/node_modules/iobroker.pid/main.js:388:35) at Pid.emit (node:events:513:28) at Immediate.<anonymous> (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:8406:53) at process.processImmediate (node:internal/timers:476:21)
pid.0 | 2023-07-09 19:39:56.379 | error | unhandled promise rejection: Cannot read properties of undefined (reading 'pidCtrl')
pid.0 | 2023-07-09 19:39:56.379 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
pid.0 | 2023-07-09 19:39:56.378 | error | Cannot read properties of undefined (reading 'pidCtrl')
pid.0 | 2023-07-09 19:39:56.378 | error | TypeError: Cannot read properties of undefined (reading 'pidCtrl') at Pid.chgAct (/opt/iobroker/node_modules/iobroker.pid/main.js:658:26) at Pid.onStateChange (/opt/iobroker/node_modules/iobroker.pid/main.js:388:35) at Pid.emit (node:events:513:28) at Immediate.<anonymous> (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:8406:53) at process.processImmediate (node:internal/timers:476:21)
pid.0 | 2023-07-09 19:39:56.378 | error | unhandled promise rejection: Cannot read properties of undefined (reading 'pidCtrl')
pid.0 | 2023-07-09 19:39:56.378 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
pid.0 | 2023-07-09 19:39:56.377 | error | Cannot read properties of undefined (reading 'pidCtrl')
pid.0 | 2023-07-09 19:39:56.377 | error | TypeError: Cannot read properties of undefined (reading 'pidCtrl') at Pid.chgAct (/opt/iobroker/node_modules/iobroker.pid/main.js:658:26) at Pid.onStateChange (/opt/iobroker/node_modules/iobroker.pid/main.js:388:35) at Pid.emit (node:events:513:28) at Immediate.<anonymous> (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:8406:53) at process.processImmediate (node:internal/timers:476:21)
pid.0 | 2023-07-09 19:39:56.376 | error | unhandled promise rejection: Cannot read properties of undefined (reading 'pidCtrl')
pid.0 | 2023-07-09 19:39:56.375 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
pid.0 | 2023-07-09 19:39:52.909 | info | processing started for 1 controller(s)
pid.0 | 2023-07-09 19:39:52.867 | info | [C-Test] controller initialized ({"xp":25,"kp":4,"tn":0,"tv":0,"min":0,"max":100,"off":0,"sup":2,"set":0,"dao":false,"inv":false,"useXp":false})
pid.0 | 2023-07-09 19:39:52.864 | info | [start] start instance with id Test
pid.0 | 2023-07-09 19:39:51.342 | info | starting. Version 0.0.7 (non-npm: iobroker-community-adapters/ioBroker.pid#623ec97e41ff01cfc7759b2179f7c1c828c876da) in /opt/iobroker/node_modules/iobroker.pid, node: v18.16.1, js-controller: 5.0.6
host.ioBroker | 2023-07-09 19:39:50.256 | info | instance system.adapter.pid.0 started with pid 3561772


</body>
</html>`

**Comment by mcm1957** [comment]
Sorry for the late reply.

I've added an additonal check to avoid crashe like shown in your log. Please feel free to update to 0.0.8 which will be available at latest tomorrow.

I'm not sure why the crashed occure in your settings. It might be that the updaterate for 'act'is very high - but thats only a guess. In no case a crash should occure. So the modified code ignores statechanges occuring while data structures are not (yet) initialized.

In regard to the original problem, please activate logging as describe above and / or check setting of limits. Note that if you expect i.e. an putput of -5 the mi imum value must be below -5. Min / Max are not changed / inverted by invert flag buet always taken as specified.

**Comment by mcm1957** [comment]
Please recheck with upcoming 1.0.0 and open a new issue if still ot wiorking.
